apiVersion: v1
kind: Pod
metadata:
  name: cybox
  labels:
    app: cybox
spec:
  containers:
  - name: cybox
    image: none
    ports:
    - containerPort: 8090
      name: ffserver
    - containerPort: 22
      name: sshd
